baseURL: "https://lonnyzhang423.github.io/"
languageCode: "zh-cn"
title: "Be a producer not a consumer"
theme: "lithium"
hasCJKLanguage: true

menu:
  main:
    - name: "GitHub"
      url: "https://github.com/lonnyzhang423"

    - name: "Twitter"
      url: "https://twitter.com/lonnyzhang423"

    - name: "关于"
      url: "/about"

params:
  author: "lonnyzhang423"
  enableToc: true
