baseURL: "https://lonnyzhang423.github.io/"
languageCode: "zh-cn"
title: "Be a producer not a consumer"
theme: "hugo-notepadium"

params: 
    nav: 
        showCategories: true
        showTags: true
    share.enable: true