name: schedule

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # 克隆仓库
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          # 同步hugo主题
          submodules: true
          fetch-depth: 0

      # 配置Hugo环境
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.79.0"

      # 配置git
      - name: Config git
        run: |
          git config --local user.email "lonnyzhang423@gmail.com"
          git config --local user.name "lonny"
          git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
          git pull --rebase

      # 部署
      - name: Deploy
        run: |
          # 基于gh-pages分支新建工作目录
          git worktree add -b gh-pages public origin/gh-pages
          rm -rf public
          # 生成网页
          hugo --minify
          cd public
          git add .
          git commit -m "auto update"
          git push origin gh-pages
